services:
  web:
    build: .
    container_name: preet-web-vision
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=file:/app/db/custom.db
      - ADMIN_EMAIL=admin@preetwebvision.com
      - ADMIN_PASSWORD=preet2025
      - NODE_ENV=production
      - PORT=3010
      - HOSTNAME=0.0.0.0
    volumes:
      - preet-data:/app/db
    restart: unless-stopped

volumes:
  preet-data:
